# Generated by Django 6.1.1 on 2026-09-04 15:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email Address')),
                ('otp_code', models.CharField(max_length=6, verbose_name='6-Digit OTP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Failed Attempts')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('purpose', models.CharField(choices=[('registration', 'Registration Verification'), ('login', 'Login Verification'), ('password_reset', 'Password Reset')], default='registration', max_length=30, verbose_name='Purpose')),
            ],
            options={
                'verbose_name': 'Email OTP',
                'verbose_name_plural': 'Email OTPs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('field_atlas_id', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Field Atlas ID')),
                ('role', models.CharField(choices=[('trainer', 'Trainer'), ('trainee', 'Trainee'), ('admin', 'Admin')], default='trainer', max_length=20, verbose_name='User Role')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi'), ('bn', 'Bengali'), ('ta', 'Tamil'), ('te', 'Telugu'), ('kn', 'Kannada'), ('gu', 'Gujarati'), ('pa', 'Punjabi'), ('ml', 'Malayalam'), ('ur', 'Urdu')], default='en', max_length=10, verbose_name='Preferred Language')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Profile Photo')),
                ('provider', models.CharField(blank=True, max_length=150, verbose_name='Training Provider / Organisation')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='District')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State')),
                ('address', models.TextField(blank=True, verbose_name='Postal Address')),
                ('bio', models.TextField(blank=True, verbose_name='Professional Bio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is Staff')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Action Performed')),
                ('target_type', models.CharField(max_length=100, verbose_name='Target Type')),
                ('target_id', models.CharField(max_length=100, verbose_name='Target Identifier')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Action Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unified_id', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Unified ID')),
                ('name', models.CharField(max_length=150, verbose_name='Learner Name')),
                ('course', models.CharField(max_length=150, verbose_name='Course')),
                ('provider', models.CharField(max_length=150, verbose_name='Training Provider')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer Not to Say')], default='prefer_not_to_say', max_length=20, verbose_name='Gender')),
                ('age_band', models.CharField(default='18-24', max_length=30, verbose_name='Age Band')),
                ('stage', models.CharField(choices=[('enrolled', 'Enrolled'), ('trained', 'Trained'), ('certified', 'Certified'), ('placed', 'Placed'), ('retained', 'Retained'), ('follow_up_due', 'Follow-up Due')], default='enrolled', max_length=30, verbose_name='Current Stage')),
                ('consent_status', models.CharField(choices=[('active', 'Active'), ('withdrawn', 'Withdrawn')], default='active', max_length=20, verbose_name='Consent Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('assigned_trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_trainees', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Trainer')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Associated User Account')),
            ],
            options={
                'verbose_name': 'Trainee',
                'verbose_name_plural': 'Trainees',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(max_length=150, verbose_name='Employer / Enterprise Name')),
                ('role', models.CharField(max_length=150, verbose_name='Job Role')),
                ('employment_type', models.CharField(choices=[('formal', 'Formal Employment'), ('self_employed', 'Self-Employed'), ('apprenticeship', 'Apprenticeship'), ('informal', 'Informal Sector')], default='formal', max_length=30, verbose_name='Employment Type')),
                ('wage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monthly Wage (INR)')),
                ('source', models.CharField(choices=[('self_reported', 'Self-Reported'), ('employer_confirmed', 'Employer-Confirmed'), ('third_party_signal', 'Third-Party Signal')], default='self_reported', max_length=30, verbose_name='Data Source')),
                ('validation_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified'), ('disputed', 'Disputed')], default='pending', max_length=30, verbose_name='Validation Status')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Employment Start Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='outcomes.trainee', verbose_name='Trainee')),
            ],
            options={
                'verbose_name': 'Placement',
                'verbose_name_plural': 'Placements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.CharField(choices=[('month_3', '3 Months Post-Training'), ('month_6', '6 Months Post-Training'), ('month_12', '12 Months Post-Training')], default='month_3', max_length=20, verbose_name='Milestone')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('ivr', 'IVR Call'), ('assisted', 'Assisted Outreach')], default='whatsapp', max_length=20, verbose_name='Outreach Channel')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('responded', 'Responded'), ('needs_assistance', 'Needs Assistance'), ('closed', 'Closed')], default='queued', max_length=30, verbose_name='Status')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Attempts Count')),
                ('due_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Due Date')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Attempt At')),
                ('response_tag', models.CharField(blank=True, max_length=100, null=True, verbose_name='Response Category')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Field Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='outcomes.trainee', verbose_name='Trainee')),
            ],
            options={
                'verbose_name': 'Follow-Up',
                'verbose_name_plural': 'Follow-Ups',
                'ordering': ['-due_at'],
            },
        ),
        migrations.CreateModel(
            name='TraineeConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_version', models.CharField(default='v1.0', max_length=20, verbose_name='Consent Policy Version')),
                ('status', models.CharField(choices=[('granted', 'Granted'), ('withdrawn', 'Withdrawn')], default='granted', max_length=20, verbose_name='Status')),
                ('consented_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Consented At')),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True, verbose_name='Withdrawn At')),
                ('source', models.CharField(default='portal_opt_in', max_length=100, verbose_name='Source Channel')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='outcomes.trainee', verbose_name='Trainee')),
            ],
            options={
                'verbose_name': 'Trainee Consent',
                'verbose_name_plural': 'Trainee Consents',
                'ordering': ['-created_at'],
            },
        ),
    ]
