# Generated by Django 6.1.1 on 2026-09-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outcomes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Failed Login Attempts'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Account Lockout Expiry'),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Requester IP'),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='otp_hash',
            field=models.CharField(blank=True, max_length=128, verbose_name='HMAC Hash of OTP'),
        ),
        migrations.AddField(
            model_name='followup',
            name='next_contact_date',
            field=models.DateField(blank=True, null=True, verbose_name='Next Contact Date'),
        ),
        migrations.AddField(
            model_name='followup',
            name='trainer_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Trainer Outreach Notes'),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, verbose_name='6-Digit OTP (Legacy)'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('responded', 'Responded'), ('needs_assistance', 'Needs Assistance'), ('rescheduled', 'Rescheduled'), ('closed', 'Closed')], default='queued', max_length=30, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['email', 'purpose', 'is_verified'], name='outcomes_em_email_45e5fd_idx'),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['created_at'], name='outcomes_em_created_70b882_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['status'], name='outcomes_fo_status_6261e5_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['due_at'], name='outcomes_fo_due_at_41fe63_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['trainee'], name='outcomes_fo_trainee_d58dd7_idx'),
        ),
        migrations.AddIndex(
            model_name='placement',
            index=models.Index(fields=['validation_status'], name='outcomes_pl_validat_c19c68_idx'),
        ),
        migrations.AddIndex(
            model_name='placement',
            index=models.Index(fields=['trainee'], name='outcomes_pl_trainee_126cf0_idx'),
        ),
        migrations.AddIndex(
            model_name='trainee',
            index=models.Index(fields=['unified_id'], name='outcomes_tr_unified_6ac9e8_idx'),
        ),
        migrations.AddIndex(
            model_name='trainee',
            index=models.Index(fields=['provider'], name='outcomes_tr_provide_667114_idx'),
        ),
        migrations.AddIndex(
            model_name='trainee',
            index=models.Index(fields=['assigned_trainer'], name='outcomes_tr_assigne_644c33_idx'),
        ),
        migrations.AddIndex(
            model_name='trainee',
            index=models.Index(fields=['stage'], name='outcomes_tr_stage_52f458_idx'),
        ),
        migrations.AddIndex(
            model_name='trainee',
            index=models.Index(fields=['consent_status'], name='outcomes_tr_consent_4958a3_idx'),
        ),
    ]
