# Generated by Django 6.1.1 on 2026-09-04 17:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outcomes', '0003_normalize_provider_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Course Title')),
                ('course_code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Course Code')),
                ('description', models.TextField(blank=True, verbose_name='Course Description')),
                ('category', models.CharField(default='Vocational Skills', max_length=100, verbose_name='Category')),
                ('provider', models.CharField(blank=True, max_length=150, verbose_name='Training Provider')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='District Hub')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State')),
                ('language', models.CharField(default='English', max_length=50, verbose_name='Instruction Language')),
                ('duration_weeks', models.PositiveIntegerField(default=8, verbose_name='Duration (Weeks)')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('capacity', models.PositiveIntegerField(default=30, verbose_name='Student Capacity')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20, verbose_name='Publication Status')),
                ('certificate_eligible', models.BooleanField(default=True, verbose_name='Certificate Eligible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Course Trainer')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation', models.TextField(blank=True, verbose_name='Motivation Statement')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', max_length=20, verbose_name='Application Status')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('trainer_note', models.TextField(blank=True, null=True, verbose_name='Trainer Decision Note')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='outcomes.course', verbose_name='Course')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='Reviewer')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_applications', to='outcomes.trainee', verbose_name='Applicant Trainee')),
            ],
            options={
                'verbose_name': 'Course Application',
                'verbose_name_plural': 'Course Applications',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn'), ('failed', 'Failed')], db_index=True, default='active', max_length=20, verbose_name='Enrollment Status')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Enrolled At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('completion_percent', models.PositiveIntegerField(default=0, verbose_name='Completion Percentage')),
                ('completion_notes', models.TextField(blank=True, null=True, verbose_name='Completion Notes')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='outcomes.courseapplication', verbose_name='Originating Application')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='outcomes.course', verbose_name='Course')),
                ('marked_completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Marked Completed By')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='outcomes.trainee', verbose_name='Enrolled Learner')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Certificate Number')),
                ('verification_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Public Verification Token')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Issued At')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Generated PDF Document')),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('revoked', 'Revoked')], db_index=True, default='issued', max_length=20, verbose_name='Certificate Status')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Revoked At')),
                ('revocation_reason', models.TextField(blank=True, null=True, verbose_name='Reason for Revocation')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL, verbose_name='Issuing Trainer')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='outcomes.enrollment', verbose_name='Course Enrollment')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Notification Title')),
                ('body', models.TextField(verbose_name='Message Body')),
                ('type', models.CharField(choices=[('application', 'Course Application'), ('enrollment', 'Enrollment Update'), ('certificate', 'Certificate Issuance'), ('outcome_reminder', 'Outcome Reminder'), ('general', 'General Alert')], db_index=True, default='general', max_length=30, verbose_name='Notification Category')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Is Read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Delivered At')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Notification Recipient')),
                ('related_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='outcomes.course', verbose_name='Related Course')),
                ('related_enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='outcomes.enrollment', verbose_name='Related Enrollment')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TraineeOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('self_employed', 'Self-Employed / Own Enterprise'), ('unemployed', 'Unemployed'), ('seeking_work', 'Actively Seeking Work'), ('continuing_education', 'Continuing Higher Education / Training')], db_index=True, max_length=35, verbose_name='Current Employment Status')),
                ('employer_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Employer or Enterprise Name')),
                ('job_role', models.CharField(blank=True, max_length=150, null=True, verbose_name='Job Role / Designation')),
                ('monthly_earning', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monthly Earnings (INR)')),
                ('employment_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Employment Contract Type')),
                ('current_district', models.CharField(blank=True, max_length=100, null=True, verbose_name='Current Working District')),
                ('current_state', models.CharField(blank=True, max_length=100, null=True, verbose_name='Current Working State')),
                ('response_notes', models.TextField(blank=True, null=True, verbose_name='Trainee Qualitative Notes')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('verification_status', models.CharField(choices=[('self_reported', 'Self Reported'), ('verified', 'Verified by Trainer'), ('disputed', 'Disputed')], db_index=True, default='self_reported', max_length=20, verbose_name='Verification Status')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='outcomes.enrollment', verbose_name='Linked Course Enrollment')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_outcomes', to=settings.AUTH_USER_MODEL, verbose_name='Verified By')),
            ],
            options={
                'verbose_name': 'Trainee Outcome',
                'verbose_name_plural': 'Trainee Outcomes',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', 'start_date', 'end_date'], name='outcomes_co_status_6dde72_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['trainer', 'status'], name='outcomes_co_trainer_1c87af_idx'),
        ),
        migrations.AddIndex(
            model_name='courseapplication',
            index=models.Index(fields=['course', 'status'], name='outcomes_co_course__4ab9ab_idx'),
        ),
        migrations.AddIndex(
            model_name='courseapplication',
            index=models.Index(fields=['trainee', 'status'], name='outcomes_co_trainee_911f6e_idx'),
        ),
        migrations.AddConstraint(
            model_name='courseapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'approved'])), fields=('course', 'trainee'), name='unique_active_application_per_trainee_course'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course', 'status'], name='outcomes_en_course__bb085e_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['trainee', 'status'], name='outcomes_en_trainee_777592_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('course', 'trainee'), name='unique_enrollment_per_trainee_course'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', 'created_at'], name='outcomes_no_recipie_d3f5da_idx'),
        ),
        migrations.AddIndex(
            model_name='traineeoutcome',
            index=models.Index(fields=['employment_status', 'verification_status'], name='outcomes_tr_employm_ddd617_idx'),
        ),
    ]
