# Generated by Django 6.1.1 on 2026-09-09 14:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outcomes', '0005_alter_course_end_date_alter_course_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='attrition_reason',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Reason for Job Change or Exit'),
        ),
        migrations.AddField(
            model_name='followup',
            name='escalated_to_mobilizer',
            field=models.BooleanField(default=False, verbose_name='Escalated to Village Mobilizer'),
        ),
        migrations.AddField(
            model_name='followup',
            name='escalation_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Mobilizer Outreach Escalation Notes'),
        ),
        migrations.AddField(
            model_name='followup',
            name='reported_wage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Updated Wage at Milestone (INR)'),
        ),
        migrations.AddField(
            model_name='placement',
            name='apprenticeship_contract_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apprenticeship Contract / NAPS ID'),
        ),
        migrations.AddField(
            model_name='placement',
            name='employer_contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Employer HR Contact Email'),
        ),
        migrations.AddField(
            model_name='placement',
            name='employer_contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Employer HR Contact Phone'),
        ),
        migrations.AddField(
            model_name='placement',
            name='employer_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Employer Verification Remarks'),
        ),
        migrations.AddField(
            model_name='placement',
            name='employer_verification_token',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True, verbose_name='Employer Verification Token'),
        ),
        migrations.AddField(
            model_name='placement',
            name='employer_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Employer Verified At'),
        ),
        migrations.AddField(
            model_name='placement',
            name='enterprise_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Enterprise / Venture Name'),
        ),
        migrations.AddField(
            model_name='placement',
            name='monthly_net_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monthly Net Profit (INR)'),
        ),
        migrations.AddField(
            model_name='placement',
            name='training_relevance',
            field=models.CharField(choices=[('directly_related', 'Directly Related'), ('partially_related', 'Partially Related'), ('unrelated', 'Unrelated')], default='directly_related', max_length=30, verbose_name='Relevance of Training'),
        ),
        migrations.AddField(
            model_name='placement',
            name='udyam_registration_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Udyam MSME Registration Number'),
        ),
        migrations.AddField(
            model_name='placement',
            name='workers_employed',
            field=models.PositiveIntegerField(default=0, verbose_name='Additional Workers Employed'),
        ),
        migrations.AddField(
            model_name='trainee',
            name='alternate_phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Alternate / Secondary Phone'),
        ),
        migrations.AddField(
            model_name='trainee',
            name='baseline_wage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Pre-Training Baseline Monthly Wage (INR)'),
        ),
        migrations.AddField(
            model_name='trainee',
            name='secondary_contact_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Secondary Contact Name'),
        ),
        migrations.AddField(
            model_name='trainee',
            name='secondary_contact_relation',
            field=models.CharField(blank=True, max_length=50, verbose_name='Secondary Contact Relationship'),
        ),
        migrations.AddField(
            model_name='traineeoutcome',
            name='apprenticeship_contract_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apprenticeship Contract ID'),
        ),
        migrations.AddField(
            model_name='traineeoutcome',
            name='attrition_reason',
            field=models.CharField(blank=True, choices=[('low_wage_growth', 'Low wage growth or delayed salary'), ('poor_work_environment', 'Poor work environment or long hours'), ('long_commute_relocation', 'Excessive commute or forced relocation'), ('better_offer', 'Secured better career opportunity'), ('family_personal', 'Family / health reasons'), ('contract_ended', 'Apprenticeship / fixed contract ended')], max_length=50, null=True, verbose_name='Reason for Attrition'),
        ),
        migrations.AddField(
            model_name='traineeoutcome',
            name='enterprise_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Enterprise / Business Name'),
        ),
        migrations.AddField(
            model_name='traineeoutcome',
            name='monthly_net_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monthly Net Profit (INR)'),
        ),
        migrations.AddField(
            model_name='traineeoutcome',
            name='non_placement_reason',
            field=models.CharField(blank=True, choices=[('skill_mismatch', 'Skill mismatch with job requirements'), ('no_local_demand', 'No local job demand / industry vacancies'), ('location_migration', 'Location / Migration barrier'), ('family_social', 'Family / Social constraints'), ('wage_expectations', 'Offered wage below expectations'), ('continuing_education', 'Opted for higher education / further training'), ('health_personal', 'Health or personal reasons')], max_length=50, null=True, verbose_name='Reason for Non-Placement'),
        ),
        migrations.AddField(
            model_name='traineeoutcome',
            name='skill_gap',
            field=models.CharField(blank=True, choices=[('practical_tools', 'Practical hands-on & modern tool proficiency'), ('communication_english', 'Professional communication & spoken English'), ('domain_theory', 'Core technical domain knowledge'), ('interview_prep', 'Interview preparedness & aptitude testing'), ('digital_literacy', 'Digital literacy & workplace software'), ('none', 'No significant skill gap')], max_length=50, null=True, verbose_name='Key Identified Skill Gap'),
        ),
        migrations.AddField(
            model_name='traineeoutcome',
            name='training_relevance',
            field=models.CharField(choices=[('directly_related', 'Directly Related'), ('partially_related', 'Partially Related'), ('unrelated', 'Unrelated')], default='directly_related', max_length=30, verbose_name='Relevance of Training'),
        ),
        migrations.AddField(
            model_name='traineeoutcome',
            name='udyam_registration_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Udyam MSME Registration Number'),
        ),
        migrations.AddField(
            model_name='traineeoutcome',
            name='workers_employed',
            field=models.PositiveIntegerField(default=0, verbose_name='Additional Workers Employed'),
        ),
    ]
