# Generated by Django 6.1.1 on 2026-09-10 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outcomes', '0006_followup_attrition_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi'), ('bn', 'Bengali'), ('ta', 'Tamil'), ('te', 'Telugu'), ('kn', 'Kannada'), ('gu', 'Gujarati'), ('pa', 'Punjabi'), ('ml', 'Malayalam'), ('ur', 'Urdu'), ('or', 'Odia')], default='en', max_length=10, verbose_name='Preferred Language'),
        ),
        migrations.CreateModel(
            name='TrainerCourseFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_behavior_rating', models.PositiveSmallIntegerField(default=5, verbose_name='Trainer Behavior & Attitude (1-5)')),
                ('trainer_teaching_rating', models.PositiveSmallIntegerField(default=5, verbose_name='Class & Teaching Quality (1-5)')),
                ('trainer_doubt_clearing_rating', models.PositiveSmallIntegerField(default=5, verbose_name='Doubt Clearing & Help (1-5)')),
                ('course_practical_rating', models.PositiveSmallIntegerField(default=5, verbose_name='Lab & Practical Quality (1-5)')),
                ('course_content_rating', models.PositiveSmallIntegerField(default=5, verbose_name='Course Content & Relevance (1-5)')),
                ('overall_score', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='Computed Overall Rating')),
                ('feedback_tags', models.JSONField(blank=True, default=list, verbose_name='Pictorial Feedback Tags')),
                ('opinion_text', models.TextField(blank=True, null=True, verbose_name='Trainee Opinion / Notes')),
                ('would_recommend', models.BooleanField(default=True, verbose_name='Would Recommend Course & Trainer')),
                ('status', models.CharField(default='submitted', max_length=20, verbose_name='Submission Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='outcomes.course', verbose_name='Rated Course')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='outcomes.trainee', verbose_name='Reviewing Trainee')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Rated Trainer')),
            ],
            options={
                'verbose_name': 'Trainer & Course Feedback',
                'verbose_name_plural': 'Trainer & Course Feedbacks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['trainer', 'created_at'], name='outcomes_tr_trainer_492457_idx'), models.Index(fields=['course', 'created_at'], name='outcomes_tr_course__972f42_idx'), models.Index(fields=['trainee', 'created_at'], name='outcomes_tr_trainee_c3b427_idx')],
            },
        ),
    ]
